book_sort/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('bookshelf-admin/', admin.site.urls),
    path('', include('users.urls', namespace="users")),
    path('bookshelf/', include('bookshelf.urls', namespace="bookshelf")),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/urls.py
from django.urls import path
from .views import (
    BookCreateView,
    BookListView,
    BookDeleteView,
    BookshelfCreateView,
    BookUpdateView,
    BookshelfUpdateView,
    bookshelf_view
)

app_name = 'bookshelf'


urlpatterns = [
    path('', bookshelf_view, name="bookshelf-view"),
    path('book/<int:pk>/update/', BookUpdateView.as_view(), name="book-update"),
    path('book/<int:pk>/delete/', BookDeleteView.as_view(), name="book-delete"),
    path('name-bookshelf/', BookshelfCreateView.as_view(), name="bookshelf-create"),
    path('rename-bookshelf/<int:pk>/', BookshelfUpdateView.as_view(), name="bookshelf-update"),
    path('add-book/', BookCreateView.as_view(), name="book-create"),
    path('book-list/', BookListView.as_view(), name="book-list"),
]

users/urls.py
from django.urls import path

from .views import index, profile, RegisterView

app_name = 'users'


urlpatterns = [
    path('', index, name="index"),
    path('profile/', profile, name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
]

bookshelf/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


class Bookshelf(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.name}'


class Book(models.Model):
    isbn = models.CharField(verbose_name='ISBN number', max_length=30)
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=30)
    spine_width = models.FloatField(max_length=5)
    spine_height = models.FloatField(max_length=5)
    spine_color = models.CharField(max_length=20)
    image = models.ImageField(default='default.jpg', upload_to='spine_photos')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

        img2 = img.resize((1, 1))
        color = img2.getpixel((0, 0))
        self.spine_color = '#{:02x}{:02x}{:02x}'.format(*color)
        super(Book, self).save(*args, **kwargs)

bookshelf/forms.py
from django import forms
from .models import Book, Bookshelf


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['isbn', 'title', 'author', 'spine_width', 'spine_height', 'image']

class BookshelfCreateForm(forms.ModelForm):
    class Meta:
        model = Bookshelf
        fields = ['name']

bookshelf/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import BookCreateForm, BookshelfCreateForm
from .models import Book, Bookshelf


@login_required
def bookshelf_view(request):
    user = request.user
    context = {
        'user': user,
        'bookshelf': Bookshelf.objects.get(user=user),
        'books': Book.objects.filter(user=user)
    }
    return render(request, 'bookshelf_view.html', context)


class BookshelfCreateView(LoginRequiredMixin, CreateView):
    template_name = 'bookshelf_create.html'
    form_class = BookshelfCreateForm

    def get_success_url(self):
        return reverse("bookshelf:bookshelf-view")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BookshelfUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'bookshelf_update.html'
    queryset = Bookshelf.objects.all()
    form_class = BookshelfCreateForm

    def get_success_url(self):
        return reverse("users:profile")


class BookCreateView(LoginRequiredMixin, CreateView):
    template_name = 'book_create.html'
    form_class = BookCreateForm

    def get_success_url(self):
        return reverse("bookshelf:bookshelf-view")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = 'book_list.html'
    context_object_name = 'books'

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        return qs.filter(user=user)


class BookUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'book_update.html'
    queryset = Book.objects.all()
    form_class = BookCreateForm
    context_object_name = "book"

    def get_success_url(self):
        return reverse("bookshelf:book-list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BookDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'book_delete.html'

    def get_queryset(self):
        user = self.request.user
        return Book.objects.filter(user=user)

    def get_success_url(self):
        return reverse('bookshelf:book-list')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BookSortofArt</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">


  </head>
  <body>

    <!-- Mobile header -->
    <div class="d-md-none">
      <header class="header">
        <nav>
          <div class="col-8 mx-auto">
            <div class="row">
              <div class="col-12 text-center">
                <h2><a href="#">Book Sort of Art</a></h2>
              </div>
              <div class="col-12 text-center border-top">
                {% if request.user.is_authenticated %}
                <a href="{% url 'users:profile' %}">Profile&nbsp;</a>
                <a href="{% url 'logout' %}" class="mt-1">&nbsp;Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="mt-1">Login&nbsp;</a>
                <a href="{% url 'users:register' %}">&nbsp;Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    </div>

    <!-- Desktop header -->
    <div class="d-none d-md-block">
      <header class="header">
        <nav>
          <div class="col-8 mx-auto">
            <div class="row">
              <div class="col-7">
                <h3><a href="#">Book Sort of Art</a></h3>
              </div>
              <div class="col-5">
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="mt-1 float-end">Logout</a>
                <a href="{% url 'users:profile' %}" class="mt-1 float-end">Profile&nbsp;&nbsp;</a>
                {% else %}
                <a href="{% url 'users:register' %}" class="mt-1 float-end">Register</a>
                <a href="{% url 'login' %}" class="mt-1 float-end">Login&nbsp;&nbsp;</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    </div>

    <div class="row mb-5" >
      {% block content %}{% endblock %}
    </div>

    <scrS src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

  </body>
</html>

templates/base_bookshelf.html
{% load static %}

<!doctype html>
<html lang="">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BookSortofArt: Bookshelf</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

	<style>
		.book:hover {
			stroke-width: 2;
			cursor: pointer;
		}
	</style>
  <meta name="theme-color" content="#fafafa">
</head>

<body>

  <!-- Mobile header -->
    <div class="d-md-none">
      <header class="header">
        <nav>
          <div class="col-8 mx-auto">
            <div class="row">
              <div class="col-12 text-center">
                <h2><a href="#">Book Sort of Art</a></h2>
              </div>
              <div class="col-12 text-center border-top">
                {% if request.user.is_authenticated %}
                <a href="{% url 'users:profile' %}">Profile&nbsp;</a>
                <a href="{% url 'logout' %}" class="mt-1">&nbsp;Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="mt-1">Login&nbsp;</a>
                <a href="{% url 'users:register' %}">&nbsp;Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    </div>

    <!-- Desktop header -->
    <div class="d-none d-md-block">
      <header class="header">
        <nav>
          <div class="col-8 mx-auto">
            <div class="row">
              <div class="col-7">
                <h3><a href="#">Book Sort of Art</a></h3>
              </div>
              <div class="col-5">
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="mt-1 float-end">Logout</a>
                <a href="{% url 'users:profile' %}" class="mt-1 float-end">Profile&nbsp;&nbsp;</a>
                {% else %}
                <a href="{% url 'users:register' %}" class="mt-1 float-end">Register</a>
                <a href="{% url 'login' %}" class="mt-1 float-end">Login&nbsp;&nbsp;</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    </div>

  <div class="mt-4">
    {% block content %}{% endblock %}
  </div>

  <!-- Mobile bookshelf -->
  <div class="d-md-none mb-5">
    <div class="container">
      <div style="text-align: center">
        <svg xmlns="http://www.w3.org/2000/svg" width="570" height="623" viewBox="0 0 570 623" style="margin: 30px auto">
          <g fill="none">
            <g transform="translate(1 5)">
              <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
              <g transform="translate(0 100)">
                <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
                <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
              </g>
              <g transform="translate(0 342)">
                <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
                <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
              </g>
              <g transform="translate(0 200)">
                <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
                <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
              </g>
              <g transform="translate(0 544)">
                <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
                <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
              </g>
            </g>
            <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
            <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
            <g transform="translate(350)">
              <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
            </g>
            <g transform="translate(550)">
              <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
            </g>
          </g>
        </svg>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-6">
            <a href="{% url 'bookshelf:book-create' %}" class="btn blue-btn" role="button">Add Book</a>
          </div>
          <div class="col-6">
            <a href="{% url 'bookshelf:book-list' %}" class="btn blue-btn float-end" role="button">Book List</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Desktop bookshelf -->
  <div class="d-none d-md-block">
    <div style="text-align: center">
      <svg xmlns="http://www.w3.org/2000/svg" width="570" height="623" viewBox="0 0 570 623" style="margin: 30px auto">
        <g fill="none">
          <g transform="translate(1 5)">
            <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
            <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
            <g transform="translate(0 100)">
              <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
            </g>
            <g transform="translate(0 342)">
              <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
            </g>
            <g transform="translate(0 200)">
              <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
            </g>
            <g transform="translate(0 544)">
              <rect width="568" height="8.13" x=".5" y=".5" fill="#634C02"/>
              <path fill="#1E1E1E" d="M568,1 L568,8.13 L1,8.13 L1,1 L568,1 M569,0 L0,0 L0,9.13 L569,9.13 L569,0 Z"/>
            </g>
          </g>
          <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
          <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
          <g transform="translate(350)">
            <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
            <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
          </g>
          <g transform="translate(550)">
            <rect width="19" height="622" x=".5" y=".5" fill="#634C02"/>
            <path fill="#1E1E1E" d="M19,1 L19,622 L1,622 L1,1 L19,1 M20,0 L0,0 L0,623 L20,623 L20,0 Z"/>
          </g>
        </g>
      </svg>
    </div>
    <div class="col-8 mx-auto mb-5">
      <div class="row">
        <div class="col-6">
          <a href="{% url 'bookshelf:book-create' %}" class="btn blue-btn" role="button">Add Book</a>
        </div>
        <div class="col-6">
          <a href="{% url 'bookshelf:book-list' %}" class="btn blue-btn float-end" role="button">Book List</a>
        </div>
      </div>
    </div>
  </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>

  <script>
	  var bookSortDataSample1 = {
	"books": [
			{
				"shelf-one-column-zero": [
				{
					"id": 0,
					"isbn": "012345",
					"title": "Title of a Red Book",
					"author": "Name of Author",
					"dimensions": {
						"height": 58,
						"spine-width": 6,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 1,
					"isbn": "007700",
					"title": "Title of Book Two",
					"author": "Name of Author Two",
					"dimensions": {
						"height": 48,
						"spine-width": 4,
						"book-width": 6
					},
					"spine-background": "#BCCBD3"
				},
				{
					"id": 2,
					"isbn": "987654",
					"title": "Title of Book Three",
					"author": "Name of Three",
					"dimensions": {
						"height": 62,
						"spine-width": 12,
						"book-width": 6
					},
					"spine-background": "#E5E5E5"
				}
			]
		}
	]
};


	  var bookSortDataSample2 = {
	"books": [
			{
				"shelf-one-column-zero": [
				{
					"id": 0,
					"isbn": "012345",
					"title": "Title of a Red Book",
					"author": "Name of Author",
					"dimensions": {
						"height": 58,
						"spine-width": 6,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 1,
					"isbn": "007700",
					"title": "Title of Book Two",
					"author": "Name of Author Two",
					"dimensions": {
						"height": 48,
						"spine-width": 4,
						"book-width": 6
					},
					"spine-background": "#BCCBD3"
				},
				{
					"id": 2,
					"isbn": "987654",
					"title": "Title of Book Three",
					"author": "Name of Three",
					"dimensions": {
						"height": 62,
						"spine-width": 12,
						"book-width": 6
					},
					"spine-background": "#E5E5E5"
				},
				{
					"id": 3,
					"isbn": "987654",
					"title": "Title of Book Three",
					"author": "Name of Three",
					"dimensions": {
						"height": 62,
						"spine-width": 12,
						"book-width": 6
					},
					"spine-background": "#E5E5E5"
				},
				{
					"id": 4,
					"isbn": "007700",
					"title": "Title of Book Two",
					"author": "Name of Author Two",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#BCCBD3"
				},
				{
					"id": 5,
					"isbn": "012345",
					"title": "Title of Book One",
					"author": "Name of Author",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 6,
					"isbn": "012345",
					"title": "Title of Book One",
					"author": "Name of Author",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 7,
					"isbn": "012345",
					"title": "Title of Book One",
					"author": "Name of Author",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 8,
					"isbn": "012345",
					"title": "Title of Book One",
					"author": "Name of Author",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				}
			],
			"shelf-two-column-one": [
				{
					"id": 9,
					"isbn": "012345",
					"title": "Title of Book One",
					"author": "Name of Author",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#C0272D"
				},
				{
					"id": 10,
					"isbn": "007700",
					"title": "Title of Book Two",
					"author": "Name of Author Two",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#BCCBD3"
				},
				{
					"id": 11,
					"isbn": "987654",
					"title": "Title of Book Three",
					"author": "Name of Three",
					"dimensions": {
						"height": 10,
						"spine-width": 2,
						"book-width": 6
					},
					"spine-background": "#E5E5E5"
				}
			]
		}
	]
};


$(function() {
  // Generate books in JSON array order


});
	  </script>


</body>

</html>

templates/book_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <div class="content-section">

    <!-- Mobile book create -->
    <div class="d-md-none">
      <div class="container">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
            <legend class="border-bottom mt-4 mb-4">New Book</legend>
            {{ form|crispy }}
          </fieldset>
          <div class="border-top pt-3 mb-2">
            <button class="w-100 btn blue-btn" type="submit">Add Book</button>
          </div>
        </form>
        <a href="{% url 'bookshelf:bookshelf-view' %}" class="w-100 btn gray-btn" role="button">Back</a>
      </div>
    </div>

    <!-- Desktop book create -->
    <div class="d-none d-md-block">
      <div class="col-8 mx-auto">
        <div class="row">
          <div class="col-6">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mt-4 mb-4">New Book</legend>
              {{ form|crispy }}
            </fieldset>
            <div class="border-top pt-3 mb-2">
              <a href="{% url 'bookshelf:bookshelf-view' %}" class="btn gray-btn" role="button">Back</a>
              <button class="btn blue-btn" type="submit">Add Book</button>
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

templates/book_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <div class="content-section">

    <div class="col-8 mx-auto mt-4">
      {% if books %}
        <div class="row">
        {% for book in books %}
          <div class="col-12 col-sm-6 col-md-4 col-lg-3" style="text-align: center; margin-top: 2em;">
            <a class="text-decoration-none" href="{% url 'bookshelf:book-update' book.pk %}"><img class="mb-2" style="height: 20em;" src="{{ book.image.url }}" /><br />
            <h4 class="border-top">{{ book.title }}</h4></a>
          </div>
        {% endfor %}
        </div>
      {% else %}
        <p>No books added</p>
      {% endif %}
      <div class="mt-5">
        <a href="{% url 'bookshelf:bookshelf-view' %}" class="btn blue-btn" role="button">Back</a>
      </div>
    </div>

  </div>

{% endblock content %}

templates/book_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <div class="content-section">

    <!-- Mobile book update -->
    <div class="d-md-none">
      <div class="container">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
            <legend class="border-bottom mt-4 mb-4">Update Book</legend>
            {{ form|crispy }}
            <p class="mt-1"><b>Average color:</b> {{ book.spine_color }}</p>
          </fieldset>
          <div class="border-top pt-3">
            <button class="w-100 btn blue-btn" type="submit">Update</button>
            <div class="row">
              <div class="col-6">
                <a href="{% url 'bookshelf:book-list' %}" class="w-100 btn gray-btn mt-3" role="button">Back</a>
              </div>
              <div class="col-6">
                <a href="{% url 'bookshelf:book-delete' book.pk %}" class="w-100 btn btn-danger mt-3" role="button">Delete</a>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>

    <!-- Desktop book update -->
    <div class="d-none d-md-block">
      <div class="col-8 mx-auto">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
            <legend class="border-bottom mt-4 mb-4">Update Book</legend>
            {{ form|crispy }}
            <p class="mt-1"><b>Average color:</b> {{ book.spine_color }}</p>
          </fieldset>
          <div class="border-top pt-3">
            <a href="{% url 'bookshelf:book-list' %}" class="btn gray-btn" role="button">Back</a>
            <a href="{% url 'bookshelf:book-delete' book.pk %}" class="btn btn-danger" role="button">Delete</a>
            <button class="btn blue-btn" type="submit">Update</button>
          </div>
        </form>
      </div>
    </div>

  </div>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="col-12 col-md-10 col-lg-6 mx-auto text-center mt-5">
      <h1>WELCOME<br />TO<br />{ BOOK SORT of ART }</h1>
      <a href="{% url 'login' %}" class="btn btn-primary col-12 mt-3" role="button">Login</a>
      <a href="{% url 'users:register' %}" class="btn btn-primary col-12 mt-3" role="button">Register</a>
    </div>
  </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

  <div class="content-section">

    <!-- Mobile profile -->
    <div class="d-md-none">
      <div class="container">
        <div class="row border-bottom mt-4">
          <h1>Welcome<br />{{ user.username|upper }}!</h1>
        </div>
        <div class="row mt-4">
          <p class="h4 mb-1">Your bookshelf:</p>
        </div>
        <div class="row">
          {% if bookshelf %}
            <div class="col-6">
              <a class="text-decoration-none" href="{% url 'bookshelf:bookshelf-view' %}">{{ bookshelf.name }}</a>
            </div>
            <div class="col-12">
              <a href="{% url 'bookshelf:bookshelf-update' bookshelf.pk %}" class="w-100 btn blue-btn mt-4" role="button">Rename bookshelf</a>
            </div>
          {% else %}
            <a href="{% url 'bookshelf:bookshelf-create' %}">Name your bookshelf</a>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Desktop profile -->
    <div class="d-none d-md-block">
      <div class="col-8 mx-auto">
        <div class="row border-bottom mt-4">
          <h1>Welcome<br />{{ user.username|upper }}!</h1>
        </div>
        <div class="row mt-4">
          <p class="h3 mb-1">Your bookshelf:</p>
        </div>
        <div class="row">
          {% if bookshelf %}
            <div class="col-6">
              <a class="text-decoration-none" href="{% url 'bookshelf:bookshelf-view' %}">{{ bookshelf.name }}</a>
            </div>
            <div class="col-12">
              <a href="{% url 'bookshelf:bookshelf-update' bookshelf.pk %}" class="btn blue-btn mt-4" role="button">Rename bookshelf</a>
            </div>
          {% else %}
            <a href="{% url 'bookshelf:bookshelf-create' %}">Name your bookshelf</a>
          {% endif %}
        </div>
      </div>
    </div>

  </div>

{% endblock content %}